// UI strings. The Tamil text was drafted for this prototype; have a Tamil-speaking
// agronomist review it before field use.
export const STRINGS = {
  en: {
    tagline: "Rice blast early warning · field officer view",
    research: "Research data",
    nav_officer: "Officer view",
    nav_live: "Live",
    nav_confidence: "Forecast confidence",
    live_on: "Live",
    live_off: "Reconnecting…",
    p_high: (p) => `${p}% High`,
    p_high_tip: (p, n) => `Ensemble: ${p}% of ${n} forecasts score this night High`,
    toast_change: (d, day, from, to, cause) => `${d} · ${day}: ${from ?? "—"} → ${to} (${cause})`,
    toast_alert: (names) => `New farmer alert ready: ${names}`,
    toast_refresh: "Forecast refreshed",
    blocks_title: "Blocks · where to scout first",
    blocks_hint: "Each block scored at its headquarters town with the same rules; risk score for the next 3 days. \"n/m blocks\" under each day above counts the blocks rated High. The district's action still comes from the district headquarters.",
    blocks_none: "No block data for this district yet.",
    blocks_stale: "Block forecast is out of date; showing the last good data.",
    blocks_high: (n, total) => `${n}/${total} blocks`,
    blocks_tip: (n, total, names) => `High in ${n} of ${total} blocks${names.length ? `: ${names.join(", ")}` : ""}`,
    block: "Block",
    rule_hq: "District HQ (Rule A)",
    rule_blocks: "Half the blocks (Rule B)",
    rule_line: (used, other, otherAction) => `Action by ${used}. ${other} would say: ${otherAction}.`,
    rule_no_blocks: "Rule B unavailable (no current block data).",
    col_block_max: "3-day max",
    col_wet_run: "Wet run",
    col_farmers: "Farmers",
    block_msg_title: (b) => `Message for ${b} block`,
    block_msg_hint: "Select a block in the table for a message worded for that block's farmers group.",
    block_msg_none: (b, reason) => `No message for ${b}: ${reason}.`,
    summary_alert: "alert farmers",
    summary_watch: "watch",
    summary_none: "no action",
    action_alert: "Alert farmers",
    action_watch: "Watch",
    action_none: "No action",
    action_unknown: "No data",
    level_Low: "Low",
    level_Moderate: "Moderate",
    level_High: "High",
    todo_alert: "Weather favours blast on several of the next 3 days. Scout fields; recommend spraying only where lesions are found. Review and forward the farmer message below.",
    todo_watch: "Weather is turning favourable for blast. Plan field scouting.",
    todo_none: "Weather is not currently favourable for blast.",
    todo_unknown: "No current forecast for this district.",
    near: "Next 3 days",
    outlook: "Later (less certain)",
    wet_hours: "leaf-wet hours",
    fresh: (h, src) => `Forecast updated ${h} h ago (${src}).`,
    stale: (h) => `Forecast is ${h} h old; showing the last good data. Refresh is retrying.`,
    expired: "Forecast data is out of date. Alerts are paused until it updates.",
    never: "No forecast has been loaded yet.",
    messages: "Message for farmers",
    copy: "Copy",
    copied: "Copied",
    mark_sent: "Mark as sent",
    sent: "Sent",
    no_message: "No message needed right now.",
    generated: (t) => `Generated ${t} from the forecast shown above.`,
    farmers_line: (n, s, r) => `${n} enrolled farmers, ${s} with crops at a blast-susceptible stage; ${r} reports to verify. `
      + "Enrolled farmers get their own message for their variety and stage. The text below is for your district WhatsApp group.",
    field_check: "Field check",
    field_check_hint: "After scouting, record what you found. Lesions show 5–7 days after the high-risk nights. Routine visits without an alert count too: each check becomes data to calibrate the model.",
    found_yes: "Blast found",
    found_no: "No blast found",
    after_alert: "after alert",
    score: "score",
    why_run: (h) => `longest wet run ${h} h`,
    why_hours: (h) => `${h} wet h`,
    why_rain: (mm) => `rain ${mm} mm`,
    why_cloud: (c) => `cloud ${c}%`,
    basis: { sensor: "field sensor", lwp: "modelled leaf wetness", dpd: "dew point", rh: "humidity" },
    based_on: "Based on",
    chart_lwp: "Leaf wetness %",
    chart_temp: "Temp °C",
    footer: "Decision support only. The risk thresholds are set so that High is uncommon in season (about 1 day in 5 over 2024–2026); they are not yet calibrated against field outbreaks. Always confirm in the field before recommending a spray.",
  },
  ta: {
    tagline: "நெல் குலை நோய் முன்னெச்சரிக்கை · கள அலுவலர் பார்வை",
    research: "ஆய்வுத் தரவு",
    nav_officer: "அலுவலர் பார்வை",
    nav_live: "நேரலை",
    nav_confidence: "முன்னறிவிப்பு நம்பகத்தன்மை",
    live_on: "நேரலை",
    live_off: "மீண்டும் இணைக்கிறது…",
    p_high: (p) => `${p}% அதிகம்`,
    p_high_tip: (p, n) => `குழு முன்னறிவிப்பு: ${n} முன்னறிவிப்புகளில் ${p}% இந்த இரவை ‘அதிகம்’ எனக் கணிக்கின்றன`,
    toast_change: (d, day, from, to, cause) => `${d} · ${day}: ${from ?? "—"} → ${to} (${cause})`,
    toast_alert: (names) => `புதிய விவசாயி எச்சரிக்கை தயார்: ${names}`,
    toast_refresh: "முன்னறிவிப்பு புதுப்பிக்கப்பட்டது",
    blocks_title: "ஒன்றியங்கள் · முதலில் எங்கு ஆய்வு செய்வது",
    blocks_hint: "ஒவ்வொரு ஒன்றியமும் அதன் தலைமையிட ஊரில் அதே விதிகளால் மதிப்பிடப்படுகிறது; அடுத்த 3 நாட்களுக்கான அபாய மதிப்பெண். மேலே ஒவ்வொரு நாளின் கீழும் உள்ள \"n/m\" ‘அதிகம்’ என மதிப்பிடப்பட்ட ஒன்றியங்களின் எண்ணிக்கை. மாவட்ட நடவடிக்கை மாவட்டத் தலைமையிடத்தை அடிப்படையாகக் கொண்டது.",
    blocks_none: "இந்த மாவட்டத்திற்கு இன்னும் ஒன்றியத் தரவு இல்லை.",
    blocks_stale: "ஒன்றிய முன்னறிவிப்பு பழையது; கடைசியாகக் கிடைத்த தரவு காட்டப்படுகிறது.",
    blocks_high: (n, total) => `${n}/${total} ஒன்றியம்`,
    blocks_tip: (n, total, names) => `${total} ஒன்றியங்களில் ${n} இல் அதிகம்${names.length ? `: ${names.join(", ")}` : ""}`,
    block: "ஒன்றியம்",
    rule_hq: "மாவட்டத் தலைமையிடம் (விதி A)",
    rule_blocks: "பாதி ஒன்றியங்கள் (விதி B)",
    rule_line: (used, other, otherAction) => `நடவடிக்கை: ${used}. ${other} படி: ${otherAction}.`,
    rule_no_blocks: "விதி B கிடைக்கவில்லை (தற்போதைய ஒன்றியத் தரவு இல்லை).",
    col_block_max: "3 நாள் அதிகபட்சம்",
    col_wet_run: "தொடர் ஈரம்",
    col_farmers: "விவசாயிகள்",
    block_msg_title: (b) => `${b} வட்டாரத்திற்கான செய்தி`,
    block_msg_hint: "அந்த வட்டார விவசாயிகள் குழுவிற்கான செய்திக்கு அட்டவணையில் ஒரு ஒன்றியத்தைத் தேர்ந்தெடுக்கவும்.",
    block_msg_none: (b, reason) => `${b}: செய்தி இல்லை (${reason}).`,
    summary_alert: "விவசாயிகளுக்கு எச்சரிக்கை",
    summary_watch: "கண்காணிப்பு",
    summary_none: "நடவடிக்கை இல்லை",
    action_alert: "விவசாயிகளுக்கு எச்சரிக்கை",
    action_watch: "கண்காணிக்கவும்",
    action_none: "நடவடிக்கை தேவையில்லை",
    action_unknown: "தரவு இல்லை",
    level_Low: "குறைவு",
    level_Moderate: "மிதம்",
    level_High: "அதிகம்",
    todo_alert: "அடுத்த 3 நாட்களில் பல நாட்கள் குலை நோய்க்கு சாதகமான வானிலை. வயல்களை ஆய்வு செய்யவும்; புள்ளிகள் உள்ள இடங்களில் மட்டும் மருந்து தெளிக்க பரிந்துரைக்கவும். கீழே உள்ள செய்தியைச் சரிபார்த்து விவசாயிகளுக்கு அனுப்பவும்.",
    todo_watch: "வானிலை குலை நோய்க்கு சாதகமாக மாறுகிறது. வயல் ஆய்வைத் திட்டமிடவும்.",
    todo_none: "தற்போது குலை நோய்க்கு சாதகமான வானிலை இல்லை.",
    todo_unknown: "இந்த மாவட்டத்திற்கு தற்போதைய முன்னறிவிப்பு இல்லை.",
    near: "அடுத்த 3 நாட்கள்",
    outlook: "பின்வரும் நாட்கள் (குறைந்த உறுதி)",
    wet_hours: "இலை ஈரமான மணிநேரம்",
    fresh: (h, src) => `முன்னறிவிப்பு ${h} மணி நேரம் முன் புதுப்பிக்கப்பட்டது (${src}).`,
    stale: (h) => `முன்னறிவிப்பு ${h} மணி நேரம் பழையது; கடைசியாகக் கிடைத்த தரவு காட்டப்படுகிறது.`,
    expired: "முன்னறிவிப்பு தரவு காலாவதியானது. புதுப்பிக்கும் வரை எச்சரிக்கைகள் நிறுத்தப்பட்டுள்ளன.",
    never: "இன்னும் முன்னறிவிப்பு ஏற்றப்படவில்லை.",
    messages: "விவசாயிகளுக்கான செய்தி",
    copy: "நகலெடு",
    copied: "நகலெடுக்கப்பட்டது",
    mark_sent: "அனுப்பப்பட்டது எனக் குறி",
    sent: "அனுப்பப்பட்டது",
    no_message: "இப்போது செய்தி தேவையில்லை.",
    generated: (t) => `மேலே உள்ள முன்னறிவிப்பிலிருந்து ${t} அன்று உருவாக்கப்பட்டது.`,
    farmers_line: (n, s, r) => `பதிவு செய்த விவசாயிகள் ${n}; குலை நோய் தாக்கக்கூடிய பருவத்தில் ${s}; சரிபார்க்க வேண்டிய புகார்கள் ${r}. `
      + "பதிவு செய்த விவசாயிகளுக்கு அவர்களின் ரகம், பருவத்திற்கேற்ற தனிச் செய்தி செல்லும். கீழே உள்ள செய்தி மாவட்ட வாட்ஸ்அப் குழுவிற்கானது.",
    field_check: "வயல் ஆய்வு",
    field_check_hint: "வயலை ஆய்வு செய்த பின் கண்டதைப் பதிவு செய்யவும். அபாய இரவுகளுக்குப் பின் 5–7 நாட்களில் புள்ளிகள் தெரியும். எச்சரிக்கை இல்லாத வழக்கமான ஆய்வுகளும் பயன்படும்: ஒவ்வொரு பதிவும் மாதிரியைச் சரிசெய்ய உதவும் தரவு.",
    found_yes: "குலை நோய் உள்ளது",
    found_no: "குலை நோய் இல்லை",
    after_alert: "எச்சரிக்கைக்குப் பின்",
    score: "மதிப்பெண்",
    why_run: (h) => `தொடர் ஈரம் ${h} மணி`,
    why_hours: (h) => `ஈர மணிநேரம் ${h}`,
    why_rain: (mm) => `மழை ${mm} மி.மீ`,
    why_cloud: (c) => `மேகம் ${c}%`,
    basis: { sensor: "கள உணரி", lwp: "மாதிரி இலை ஈரம்", dpd: "பனி நிலை", rh: "ஈரப்பதம்" },
    based_on: "அடிப்படை",
    chart_lwp: "இலை ஈரம் %",
    chart_temp: "வெப்பநிலை °C",
    footer: "முடிவு ஆதரவு மட்டுமே. பருவத்தில் ‘அதிகம்’ அரிதாக (2024–2026 இல் சுமார் 5 நாளில் 1) வருமாறு வரம்புகள் அமைக்கப்பட்டுள்ளன; இன்னும் கள நோய்த் தரவுடன் சரிபார்க்கப்படவில்லை. மருந்து பரிந்துரைக்கும் முன் வயலில் உறுதி செய்யவும்.",
  },
};
